package UI.swingGUI;

import controller.CreateTaskHandler;
import domain.dto.DetailedProject;
import domain.dto.DetailedResourceType;
import domain.dto.DetailedTask;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * This jframe handles the create task use case.
 * 
 * @author Frederic, Mathias, Pieter-Jan
 */
public class CreateTaskFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = -2618352985080584426L;
    private final CreateTaskHandler handler;
    private DefaultTableModel prereqModel;

    /**
     * Creates new form CreateProjectFrame
     *
     * @param handler The handler to pass the requests to
     */
    public CreateTaskFrame(CreateTaskHandler handler) throws IllegalStateException {
        
        initComponents();
        this.handler = handler;
        initProjectComboBox();
               
        initTaskTables(((DetailedProject) projectComboBox.getSelectedItem()).getId());     
        initResourceTable();
    }

    /**
     * Initialize the project combobox with the projects.
     */
    private void initProjectComboBox() {
        
        for (DetailedProject project : handler.getUnfinishedProjects()) {
            projectComboBox.addItem(project);
        }

    }
    
     /**
     * Inits the resourcetype table with the resourcetypes
     */
    private void initResourceTable() {
        
        List<DetailedResourceType> resourceTypes = handler.getResourceTypes();
        Object[][] data = new Object[resourceTypes.size()][];
        int i = 0;
        for (DetailedResourceType type : resourceTypes) {
            data[i] = new Object[]{
                type.getName(),
                0};
            i++;
        }
        DefaultTableModel resourceModel = new DefaultTableModel(data, new String[]{"Name", "Quantity"});
        ResourceTypeTable.setModel(resourceModel);
    }

    /**
     * Initialize the list project table with the appropriate data
     */
    private void initTaskTables(int pId) {

        String[] columnNames = {"Id", "Description"};
        List<DetailedTask> tasks = handler.getTasksByProject(pId);
        Object[][] data = new Object[tasks.size()][];

        int i = 0;
        for (DetailedTask task : tasks) {
            data[i] = new Object[]{
                task.getId(),
                task.getDescription(),};
            i++;
        }

        prereqModel = new DefaultTableModel(data, columnNames){
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        prereqTable.setModel(prereqModel);
        prereqTable.getColumnModel().getColumn(0).setMaxWidth(50);
        alternativeForTable.setModel(prereqModel);
        alternativeForTable.getColumnModel().getColumn(0).setMaxWidth(50);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "rawtypes"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        accDevTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createTaskButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        projectComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        prereqTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alternativeForTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        estDurationMinutesTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ResourceTypeTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Estimated Duration ");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+15f));
        jLabel2.setText("New Task");

        accDevTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        accDevTextField.setToolTipText("Acceptable deviation");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Acceptable Deviation");

        createTaskButton.setText("Create");
        createTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTask(evt);
            }
        });

        jLabel6.setText("Minutes");

        jLabel7.setText("%");

        projectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Project");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane2.setViewportView(descriptionTextArea);

        prereqTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        prereqTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(prereqTable);

        jLabel5.setText("Prerequisites");

        alternativeForTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(alternativeForTable);

        jLabel9.setText("Alternative for");

        estDurationMinutesTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        estDurationMinutesTextField.setToolTipText("Estimated duration minutes");

        ResourceTypeTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        ResourceTypeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(ResourceTypeTable);

        jLabel11.setText("Required Resources");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(accDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(estDurationMinutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(390, 390, 390))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(477, 477, 477))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(480, 480, 480))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(estDurationMinutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(createTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The create task button is pressed
     * @param evt 
     */
    private void createTask(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTask
        if(projectComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(rootPane, "Please select a project.", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        int Pid = ((DetailedProject) projectComboBox.getSelectedItem()).getId();
        String description = descriptionTextArea.getText();
        int accDev = 0;
        int estDurationMinutes = 0;
        try {
            accDev = Integer.parseInt(accDevTextField.getText());
            estDurationMinutes = Integer.parseInt(estDurationMinutesTextField.getText());
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(rootPane, "Some parameters are not numbers, when they should be.", null, JOptionPane.ERROR_MESSAGE);
        }
        List<Integer> prereqs = null;
        int altFor;
        
        // check if alternative for is selected
        if (alternativeForTable.getSelectedRow() != -1) {
            altFor = (int) alternativeForTable.getValueAt(alternativeForTable.convertRowIndexToModel(alternativeForTable.getSelectedRow()), 0);
        } else {
            altFor = -1;
        }
        
        // check if prereqs are selected
        if (prereqTable.getSelectedRow() != -1) {
            int[] selectedRows = prereqTable.getSelectedRows();
            prereqs = new ArrayList<>();
            
            for (int rowId : selectedRows) {

                prereqs.add((int) prereqTable.getValueAt(prereqTable.convertRowIndexToModel(rowId), 0));
                
            }
        }
        
        Map<Integer, Integer> resources = new HashMap<>();
        // check if resourcetypes are selected
        if (ResourceTypeTable.getSelectedRow() != -1) {
            int[] selectedRows = ResourceTypeTable.getSelectedRows();
            
            for (int rowId : selectedRows) {
                resources.put(rowId, Integer.parseInt(ResourceTypeTable.getValueAt(ResourceTypeTable.convertRowIndexToModel(rowId), 1).toString()));
                
            }
        }

        try {
            handler.createTask(Pid, description, accDev, prereqs, estDurationMinutes, altFor, resources);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createTask
    
    /**
     * A project is selected in the combobox
     * 
     * @param evt 
     */
    private void projectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectComboBoxActionPerformed
        int Pid = ((DetailedProject) projectComboBox.getSelectedItem()).getId();
        initTaskTables(Pid);
    }//GEN-LAST:event_projectComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ResourceTypeTable;
    private javax.swing.JTextField accDevTextField;
    private javax.swing.JTable alternativeForTable;
    private javax.swing.JButton createTaskButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField estDurationMinutesTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable prereqTable;
    private javax.swing.JComboBox projectComboBox;
    // End of variables declaration//GEN-END:variables

   
}
